export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_ACTIVE_SERVICE_REQUEST = 'FETCH_ACTIVE_SERVICE_REQUEST';
export const FETCH_ACTIVE_SERVICE_SUCCESS = 'FETCH_ACTIVE_SERVICE_SUCCESS';
export const FETCH_ACTIVE_SERVICE_FAILURE = 'FETCH_ACTIVE_SERVICE_FAILURE';
